apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "demo-weather-fe"
  links:
    - title: Production
      url: https://demo-weather-fe.glair.id
    - title: Staging
      url: https://demo-weather-fe-staging.glair.id
    - title: Develop
      url: https://demo-weather-fe-develop.glair.id
  annotations:
    google.com/cloudbuild-project-slug: 'intern-infra'
    google.com/cloudbuild-repo-name: 'api-antrein'
    google.com/cloudbuild-location: 'asia-east1'
    github.com/project-slug: 'rey-gdp-intern/demo-weather-fe'
    backstage.io/techdocs-ref: dir:.
  dependsOn:
    - component:default/demo-weather-be
  consumesApis:
    - default/demo-weather-be-api
spec:
  type: service
  owner: group:sre
  lifecycle: experimental